project:
  type: website

website:
  title: "Neetcode 150 & SQL 50 Study Guide"
  site-url: https://srijith-reddy.github.io/NEETCODE-150-SQL-50-Study-Guide/
  repo-url: https://github.com/srijith-reddy/NEETCODE-150-SQL-50-Study-Guide
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Neetcode Python and SQL Problems.qmd
        text: Problems
    right:
      - icon: github
        href: https://github.com/srijith-reddy
      - icon: linkedin
        href: https://www.linkedin.com/in/saisrijith-reddy-maramreddy-399869166
  page-footer:
    left: "© {{< year >}} Saisrijith Reddy Maramreddy"
    right:
      - icon: github
        href: https://github.com/srijith-reddy
      - icon: linkedin
        href: https://www.linkedin.com/in/saisrijith-reddy-maramreddy-399869166

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-location: left
    code-fold: true
    code-tools: true
    anchor-sections: true
    smooth-scroll: true
    css: styles.css
  pdf:
    documentclass: article

editor: visual
